name: Calculate Astrology Chart
description: Generate Vedic or Western astrology chart from user birth data
project: astra

input_schema:
  type: object
  required:
    - birth_date
    - birth_time
    - birth_location
  properties:
    birth_date:
      type: string
      description: Date of birth in YYYY-MM-DD format
    birth_time:
      type: string
      description: Birth time in HH:MM 24-hour format
    birth_location:
      type: string
      description: Birth location as "City, Country"
    birth_timezone:
      type: string
      description: IANA timezone (e.g., "Asia/Kolkata", "America/New_York")
    chart_system:
      type: string
      enum:
        - vedic
        - western
        - both
      default: vedic
      description: Astrology system to use
    ayanamsha:
      type: string
      enum:
        - lahiri
        - raman
        - krishnamurti
        - yukteshwar
      default: lahiri
      description: Ayanamsha to use for Vedic calculations

main:
  # Step 1: Validate birth data
  - evaluate:
      has_complete_data: $ all([_.birth_date, _.birth_time, _.birth_location])

  - if: $ not _.has_complete_data
    then:
      - return:
          success: false
          error: "Incomplete birth data"
          message: "Cannot calculate chart without complete birth data (date, time, location)"
    else:
      - continue: null

  # Step 2: Generate Vedic chart calculation
  - if: $ _.chart_system in ["vedic", "both"]
    then:
      - prompt: |-
          Calculate Vedic astrology birth chart for:
          Date: {birth_date}, Time: {birth_time}, Location: {birth_location}
          Timezone: {birth_timezone or "UTC"}, Ayanamsha: {ayanamsha}

          Return ONLY valid JSON:
          {{
            "system": "vedic",
            "sun_sign": "Leo",
            "moon_sign": "Pisces",
            "ascendant": "Gemini",
            "planets": [
              {{"name": "Sun", "sign": "Leo", "house": 5, "degree": "23°45'", "nakshatra": "Magha"}},
              {{"name": "Moon", "sign": "Pisces", "house": 12, "degree": "15°30'", "nakshatra": "Revati"}},
              {{"name": "Mars", "sign": "Aries", "house": 8, "degree": "10°20'", "nakshatra": "Ashwini"}},
              {{"name": "Mercury", "sign": "Virgo", "house": 6, "degree": "12°15'", "nakshatra": "Hasta"}},
              {{"name": "Jupiter", "sign": "Sagittarius", "house": 9, "degree": "8°40'", "nakshatra": "Mula"}},
              {{"name": "Venus", "sign": "Cancer", "house": 4, "degree": "22°10'", "nakshatra": "Ashlesha"}},
              {{"name": "Saturn", "sign": "Capricorn", "house": 10, "degree": "18°25'", "nakshatra": "Shravana"}},
              {{"name": "Rahu", "sign": "Gemini", "house": 3, "degree": "5°50'", "nakshatra": "Mrigashira"}},
              {{"name": "Ketu", "sign": "Sagittarius", "house": 9, "degree": "5°50'", "nakshatra": "Mula"}}
            ],
            "house_lords": [
              {{"house": 1, "lord": "Mercury"}},
              {{"house": 2, "lord": "Venus"}},
              {{"house": 3, "lord": "Mars"}},
              {{"house": 4, "lord": "Moon"}},
              {{"house": 5, "lord": "Sun"}},
              {{"house": 6, "lord": "Mercury"}},
              {{"house": 7, "lord": "Jupiter"}},
              {{"house": 8, "lord": "Saturn"}},
              {{"house": 9, "lord": "Saturn"}},
              {{"house": 10, "lord": "Venus"}},
              {{"house": 11, "lord": "Mars"}},
              {{"house": 12, "lord": "Moon"}}
            ],
            "yogas": ["Raj Yoga", "Gaja Kesari Yoga"],
            "dasha": {{
              "mahadasha": "Jupiter",
              "antardasha": "Saturn",
              "years_remaining": 2.5
            }},
            "strengths": ["Exalted Mars in 8th", "Strong Jupiter in own sign"],
            "challenges": ["12th house Moon", "Saturn aspect on 4th house"],
            "chart_summary": "Strong spiritual tendencies with Jupiter in 9th. Leadership qualities through exalted Mars. Emotional sensitivity needs grounding."
          }}

          Calculate all 9 planets (Sun through Ketu), use sidereal zodiac with {ayanamsha} ayanamsha.
          Be accurate with houses, degrees, and nakshatras.

          birth_date = {_.birth_date}
          birth_time = {_.birth_time}
          birth_location = {_.birth_location}
          birth_timezone = {_.birth_timezone}
          ayanamsha = {_.ayanamsha}
        unwrap: true

      - evaluate:
          vedic_chart_json: $ json.loads(steps[-1].output)
    else:
      - evaluate:
          vedic_chart_json: null

  # Step 3: Generate Western chart calculation (if requested)
  - if: $ _.chart_system in ["western", "both"]
    then:
      - prompt: |-
          Calculate Western astrology birth chart for:
          Date: {birth_date}, Time: {birth_time}, Location: {birth_location}, Timezone: {birth_timezone or "UTC"}

          Return ONLY valid JSON:
          {{
            "system": "western",
            "sun_sign": "Leo",
            "moon_sign": "Pisces",
            "rising_sign": "Gemini",
            "planets": [
              {{"name": "Sun", "sign": "Leo", "house": 3, "degree": "23°45'"}},
              {{"name": "Moon", "sign": "Pisces", "house": 10, "degree": "15°30'"}},
              {{"name": "Mercury", "sign": "Virgo", "house": 4, "degree": "12°15'"}},
              {{"name": "Venus", "sign": "Cancer", "house": 2, "degree": "22°10'"}},
              {{"name": "Mars", "sign": "Aries", "house": 11, "degree": "10°20'"}},
              {{"name": "Jupiter", "sign": "Sagittarius", "house": 7, "degree": "8°40'"}},
              {{"name": "Saturn", "sign": "Capricorn", "house": 8, "degree": "18°25'"}},
              {{"name": "Uranus", "sign": "Aquarius", "house": 9, "degree": "5°50'"}},
              {{"name": "Neptune", "sign": "Pisces", "house": 10, "degree": "12°35'"}},
              {{"name": "Pluto", "sign": "Capricorn", "house": 8, "degree": "15°20'"}}
            ],
            "house_cusps": [
              {{"house": 1, "sign": "Gemini", "degree": "15°30'"}},
              {{"house": 2, "sign": "Cancer", "degree": "10°15'"}},
              {{"house": 3, "sign": "Leo", "degree": "5°40'"}}
            ],
            "aspects": [
              {{"planet1": "Sun", "planet2": "Moon", "aspect": "trine", "orb": "2°"}},
              {{"planet1": "Venus", "planet2": "Mars", "aspect": "square", "orb": "3°"}}
            ],
            "elements": {{"fire": 3, "earth": 2, "air": 3, "water": 2}},
            "modalities": {{"cardinal": 4, "fixed": 3, "mutable": 3}},
            "patterns": ["Grand Trine in Water", "T-Square involving Mars"],
            "chart_summary": "Creative and communicative with Gemini rising. Strong emotional depth from Pisces Moon. Leadership through Leo Sun."
          }}

          Use tropical zodiac, Placidus house system. Calculate all 10 planets + Ascendant.
          Include major aspects (conjunction, opposition, trine, square, sextile) with orbs.

          birth_date = {_.birth_date}
          birth_time = {_.birth_time}
          birth_location = {_.birth_location}
          birth_timezone = {_.birth_timezone}
        unwrap: true

      - evaluate:
          western_chart_json: $ json.loads(steps[-1].output)
    else:
      - evaluate:
          western_chart_json: null

  # Step 4: Return chart data for MongoDB sync
  - return:
      success: true
      chart_system: $ _.chart_system
      birth_data:
        date: $ _.birth_date
        time: $ _.birth_time
        location: $ _.birth_location
        timezone: $ _.birth_timezone
      vedic_chart: $ _.vedic_chart_json if _.vedic_chart_json else null
      western_chart: $ _.western_chart_json if _.western_chart_json else null
      calculated_at: $ datetime.now().isoformat()
      message: "Chart calculated successfully"
