import { getUsers } from "@/lib/mongo";

const users = getUsers();
const user = await users.findOne({ email: "attrishubhamwork@gmail.com" });

if (!user) {
	console.error("User not found");
	process.exit(1);
}

const overview = user.user_overview;
const storedMessage = overview?.first_message;
const userName = user.name || "Shubham Attri";

console.log(`
╔════════════════════════════════════════════════════════════════════════════╗
║               PREVIEW: YOUR NEXT CONVERSATION GREETING                     ║
╚════════════════════════════════════════════════════════════════════════════╝

🎙️  SAMAY WILL SAY:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);

if (storedMessage && storedMessage.trim().length > 0) {
	const finalMessage = storedMessage
		.replace(/\{\{user_name\}\}/g, userName)
		.replace(/\[USERNAME\]/g, userName);
	
	console.log(`"${finalMessage}"\n`);
	console.log("✅ Source: Personalized message from last conversation (PRIORITY 1)");
	console.log("✅ Generated by: Transcript processor AI task");
	console.log("✅ Stored in: MongoDB user_overview.first_message");
} else {
	const streakDays = overview?.gamification?.streak_days ?? 0;
	console.log(`(Would use streak-based fallback for streak = ${streakDays})`);
	console.log("⚠️  No stored first_message found - using fallback");
}

console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 CONTEXT DATA SAMAY HAS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Streak: ${overview?.gamification?.streak_days ?? 0} days
Total conversations: ${overview?.gamification?.total_conversations ?? 0}
Recent conversations tracked: ${overview?.recent_conversations?.length ?? 0}
Incident map items: ${overview?.incident_map?.length ?? 0}
Topics explored: ${overview?.gamification?.topics_explored?.length ?? 0}

Birth chart: ${overview?.birth_chart ? "✅ Complete" : "❌ Not calculated"}
Profile summary: ${overview?.profile_summary ? "✅ Exists" : "❌ Empty"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 WHY THIS MESSAGE?
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After your last conversation, the transcript processor:
1. Analyzed the full conversation transcript
2. Identified key themes: patience, "doing" philosophy, innovation
3. Referenced specific projects: moonshot, background agents
4. Highlighted your interests: intelligence, memory, learning
5. Generated this personalized opener for continuity

This makes Samay feel like a real companion who remembers YOUR journey!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);

process.exit(0);
